/* Kaitiaki SD-card field workflow. Separate from legacy collection and training. */
(()=>{'use strict';
const api=()=>window.KaitiakiFieldAIv4, DB='kaitiaki-field-runs-v1',STORE='runs',EXT=/\.(jpe?g|png|webp|bmp|gif|jfif)$/i;
const $=id=>document.getElementById(id),escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const classes=['Possum','Rat','Stoat','Mouse','Pig','Deer','Kereru','Tui','Kiwi','Weka','Other'];
const pests=['Possum','Stoat','Rat','Mouse','Pig','Deer'];
let runs=[],selected=null,working=false,filter='priority',page=0,objectUrls=[],selectionCamera='',liveRecord=null;
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function getRuns(){const db=await openDb();return new Promise((resolve,reject)=>{const t=db.transaction(STORE,'readonly'),q=t.objectStore(STORE).getAll();q.onsuccess=()=>resolve(q.result||[]);q.onerror=()=>reject(q.error);t.oncomplete=()=>db.close()})}
async function saveRun(run){const db=await openDb();return new Promise((resolve,reject)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put(run);t.oncomplete=()=>{db.close();resolve()};t.onerror=()=>{db.close();reject(t.error)}})}
function newId(){return crypto.randomUUID?.()||String(Date.now())+'-'+Math.random().toString(36).slice(2)}
function timestamp(file){return Number.isFinite(file.lastModified)&&file.lastModified>0?new Date(file.lastModified).toISOString():''}
function cameraFrom(path,fallback){const m=path.match(/(?:^|[\/_\s-])([A-Z]{1,4}[-_ ]?\d{2,5})(?=[\/_.\s-]|$)/i);return m?m[1].replace(/[_ ]/g,'-').toUpperCase():fallback}
function reviewReason(record){if(record.corrected)return '';if(record.error)return 'Read/decode failed';if(record.predicted==='Possum')return 'Verify every possum detection';if(record.predicted==='Stoat')return 'Verify stoat detection';if(record.review)return 'Model uncertain';if(record.predicted==='Other'&&record.scores?.slice(1,3).some(x=>pests.includes(x.label)&&x.score>=.10))return 'Possible missed pest';if(record.predicted==='Other'&&record.audit)return 'Other audit sample';return ''}
function unresolved(r){return !!reviewReason(r)}
function rankedRecords(run){return (run.records||[]).filter(r=>{if(filter==='all')return true;if(filter==='priority')return unresolved(r);if(filter==='corrected')return !!r.corrected;if(filter==='failed')return !!r.error;return r.cameraId===filter||r.predicted===filter}).sort((a,b)=>{const rank=r=>r.error?0:r.predicted==='Possum'?1:r.predicted==='Stoat'?2:r.review?3:r.predicted==='Other'?4:5;return rank(a)-rank(b)||a.name.localeCompare(b.name)})}
function counts(run,camera){const records=(run?.records||[]).filter(r=>!camera||r.cameraId===camera),out=Object.fromEntries(classes.map(c=>[c,0]));let review=0,failed=0;for(const r of records){if(r.error){failed++;review++;continue}const label=r.corrected||r.predicted;if(out[label]!==undefined)out[label]++;if(unresolved(r))review++}return{...out,review,failed,total:records.length}}
function notice(message,error=false){$('message').textContent=message;$('message').className=error?'message error':'message'}
function escapeCsv(v){const s=String(v??'');return /[",\r\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function csv(run){const headers=['run_id','camera_id','file_path','file_name','file_modified_time_approx','predicted','confidence','second_guess','second_confidence','margin','model_review','human_review_reason','final_label','reviewed_at','review_note','read_error'];return [headers,...(run.records||[]).map(r=>[run.id,r.cameraId,r.path,r.name,r.fileTime,r.predicted,r.confidence,r.scores?.[1]?.label,r.scores?.[1]?.score,r.margin,r.review?'Yes':'No',reviewReason(r),r.corrected||'',r.reviewedAt||'',r.note||'',r.error||''])].map(row=>row.map(escapeCsv).join(',')).join('\r\n')}
function download(name,data,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function cleanupUrls(){for(const url of objectUrls)URL.revokeObjectURL(url);objectUrls=[]}
function setBusy(b){working=b;for(const id of ['start','choose','cameraInput','runSelect'])if($(id))$(id).disabled=b}
function fileHandle(record){return record.handle}
async function showThumbnail(record,id){const target=$(id);if(!target||!record.handle){if(target)target.textContent='Photo unavailable — reconnect SD card';return}try{const file=await record.handle.getFile();if(!target.isConnected)return;const url=URL.createObjectURL(file);objectUrls.push(url);const img=document.createElement('img');img.src=url;img.alt=record.name;img.loading='lazy';target.replaceChildren(img)}catch{target.textContent='Reconnect the SD card to view photo'}}
function statsMarkup(c){return ['Possum','Stoat','Rat','Mouse','Other','review'].map(k=>'<div class="stat"><b>'+c[k].toLocaleString()+'</b><span>'+escapeHtml(k==='review'?'Needs review':k)+'</span></div>').join('')}
function renderCameras(){const cameras=[...new Set((selected?.records||[]).map(r=>r.cameraId))].sort(),container=$('cameras');container.innerHTML=cameras.length?cameras.map(camera=>{const c=counts(selected,camera);return '<button class="camera" data-camera="'+escapeHtml(camera)+'"><strong>'+escapeHtml(camera)+'</strong><span>Possum '+c.Possum+' · Stoat '+c.Stoat+' · Rat '+c.Rat+' · Mouse '+c.Mouse+'</span><em>'+c.review+' review</em></button>'}).join(''):'<p class="muted">No camera results yet.</p>';container.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{filter=b.dataset.camera;page=0;renderReview();$('reviewSection').scrollIntoView({behavior:'smooth'})})}
function renderHistory(){const sel=$('runSelect');sel.innerHTML=runs.slice().sort((a,b)=>b.created.localeCompare(a.created)).map(r=>'<option value="'+escapeHtml(r.id)+'">'+escapeHtml(r.cameraFallback+' · '+new Date(r.created).toLocaleString()+' · '+r.records.length+' images')+'</option>').join('');if(selected)sel.value=selected.id}
function renderReview(){cleanupUrls();const items=selected?rankedRecords(selected):[],limit=36,start=page*limit,part=items.slice(start,start+limit);$('reviewCount').textContent=items.length+' images';$('reviewList').innerHTML=part.length?part.map((r,i)=>{const id='photo-'+i,reason=reviewReason(r);return '<article class="review-card"><div class="photo" id="'+id+'"><span>Loading photo…</span></div><div class="details"><div class="row"><strong>'+escapeHtml(r.cameraId)+' · '+escapeHtml(r.name)+'</strong><span class="pill '+(reason?'warn':'')+'">'+escapeHtml(reason||'Reviewed')+'</span></div><p class="muted">'+escapeHtml(r.path)+'<br>File modified: '+escapeHtml(r.fileTime?new Date(r.fileTime).toLocaleString():'Not available')+' (not verified capture time)</p><p><strong>'+escapeHtml(r.predicted||'Failed')+'</strong> '+(r.confidence!=null?(r.confidence*100).toFixed(1)+'%':'')+' · Second: '+escapeHtml(r.scores?.[1]?.label||'—')+' '+(r.scores?.[1]?.score!=null?(r.scores[1].score*100).toFixed(1)+'%':'')+'</p>'+(r.error?'<p class="error">'+escapeHtml(r.error)+'</p>':'')+'<label>Confirm or correct <select data-change="'+escapeHtml(r.id)+'"><option value="">Choose label…</option>'+classes.map(c=>'<option value="'+c+'" '+(r.corrected===c?'selected':'')+'>'+c+'</option>').join('')+'</select></label><label>Optional note <input data-note="'+escapeHtml(r.id)+'" maxlength="250" value="'+escapeHtml(r.note||'')+'" placeholder="e.g. actually vegetation"></label><p class="muted">'+(r.reviewedAt?'Reviewed '+escapeHtml(new Date(r.reviewedAt).toLocaleString()):'Not yet reviewed')+'</p></div></article>'}).join(''):'<p class="muted">Nothing in this queue.</p>';for(let i=0;i<part.length;i++)showThumbnail(part[i],'photo-'+i);$('pageLabel').textContent=items.length?'Page '+(page+1)+' of '+Math.ceil(items.length/limit):'';$('prev').disabled=page===0;$('next').disabled=start+limit>=items.length;$('reviewList').querySelectorAll('[data-change]').forEach(el=>el.onchange=async()=>{const rec=selected.records.find(r=>r.id===el.dataset.change);if(!rec)return;rec.corrected=el.value;rec.reviewedAt=el.value?new Date().toISOString():'';await saveRun(selected);renderSummary()});$('reviewList').querySelectorAll('[data-note]').forEach(el=>el.onchange=async()=>{const rec=selected.records.find(r=>r.id===el.dataset.note);if(!rec)return;rec.note=el.value;await saveRun(selected)})}
function renderSummary(){const c=counts(selected);$('stats').innerHTML=statsMarkup(c);renderCameras();$('export').disabled=!selected;$('filter').innerHTML=['priority','all','Possum','Stoat','Rat','Mouse','Other','corrected','failed',...[...new Set((selected?.records||[]).map(r=>r.cameraId))].sort()].map(k=>'<option value="'+escapeHtml(k)+'">'+escapeHtml(({priority:'Needs review first',all:'All images',corrected:'Reviewed / corrected',failed:'Failed images'})[k]||k)+'</option>').join('');$('filter').value=filter;renderReview()}
async function setSelected(id){selected=runs.find(r=>r.id===id)||null;filter='priority';page=0;renderHistory();renderSummary();if(selected)notice((selected.completed?'Completed':'Interrupted')+' run · '+selected.records.length+' saved images. Keep the SD card connected to open thumbnails.')}
async function scan(root){const out=[];async function walk(dir,parts){for await(const [name,h] of dir.entries()){if(h.kind==='directory')await walk(h,[...parts,name]);else if(EXT.test(name))out.push({handle:h,name,path:[...parts,name].join('/')})}}await walk(root,[root.name]);return out}
async function start(){if(working)return;const model=api();if(!model){notice('V4 classifier script did not load.',true);return}const camera=$('cameraInput').value.trim().toUpperCase();if(!camera){notice('Enter camera ID first (for example D035).',true);$('cameraInput').focus();return}if(!selectionCamera){notice('Choose an SD-card folder first.',true);return}setBusy(true);try{notice('Checking the saved V4 model…');await model.loadSavedModel();notice('Reading SD-card images…');const entries=await scan(selectionCamera);if(!entries.length)throw Error('No supported images in that folder.');const run={id:newId(),created:new Date().toISOString(),cameraFallback:camera,folderName:selectionCamera.name,completed:false,records:[],total:entries.length,modelVersion:model.VERSION};runs.unshift(run);selected=run;filter='priority';page=0;await saveRun(run);let failures=0;for(let i=0;i<entries.length;i++){const e=entries[i],file=await e.handle.getFile().catch(()=>null),cameraId=cameraFrom(e.path,camera),item={id:newId(),name:e.name,path:e.path,cameraId,handle:e.handle,fileTime:file?timestamp(file):'',predicted:'',confidence:null,margin:null,scores:[],review:false,corrected:'',note:'',reviewedAt:'',error:'',audit:i%25===0};try{if(!file)throw Error('Cannot read SD card image');const r=await model.predictFile(file);Object.assign(item,{predicted:r.predicted||r.decision,confidence:r.confidence,margin:r.margin,scores:r.scores||[],review:!!r.review});}catch(err){item.error=String(err?.message||err);failures++}run.records.push(item);if((i+1)%20===0||i===entries.length-1){await saveRun(run);$('progress').value=i+1;$('progress').max=entries.length;$('progressText').textContent=(i+1).toLocaleString()+' / '+entries.length.toLocaleString()+' images · '+failures+' failed';renderSummary();await new Promise(resolve=>setTimeout(resolve,0))}}run.completed=true;await saveRun(run);renderHistory();renderSummary();notice('Classification complete. Review flagged images below. Source photos were not modified.')}catch(err){notice('Stopped: '+String(err?.message||err)+'. Saved results remain available.',true);if(selected)await saveRun(selected)}finally{setBusy(false)}}
async function init(){runs=await getRuns();renderHistory();if(runs.length)await setSelected(runs.slice().sort((a,b)=>b.created.localeCompare(a.created))[0].id);else renderSummary();$('choose').onclick=async()=>{try{selectionCamera=await showDirectoryPicker({mode:'read'});$('folder').textContent='Selected '+selectionCamera.name;notice('Ready to classify. Enter camera ID and press Classify SD Card.')}catch(err){if(err?.name!=='AbortError')notice(String(err?.message||err),true)}};$('start').onclick=start;$('runSelect').onchange=e=>setSelected(e.target.value);$('filter').onchange=e=>{filter=e.target.value;page=0;renderReview()};$('prev').onclick=()=>{page=Math.max(0,page-1);renderReview()};$('next').onclick=()=>{page++;renderReview()};$('export').onclick=()=>{if(selected)download('kaitiaki-'+selected.cameraFallback+'-'+selected.created.slice(0,10)+'.csv',csv(selected),'text/csv;charset=utf-8')};$('relink').onclick=async()=>{if(!selected)return;try{const root=await showDirectoryPicker({mode:'read'}),files=await scan(root),index=new Map(files.map(f=>[f.path.replace(/^[^/]+\//,''),f.handle]));let n=0;for(const rec of selected.records){const h=index.get(rec.path.replace(/^[^/]+\//,''));if(h){rec.handle=h;n++}}await saveRun(selected);renderReview();notice('Reconnected '+n+' photos. The original SD-card files were not changed.')}catch(e){if(e?.name!=='AbortError')notice(String(e?.message||e),true)}}}
init().catch(e=>notice('Could not load saved runs: '+e.message,true));
})();