const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../ai-trainer-v13.js'),'utf8');
const sandbox={window:{},document:{readyState:'loading',addEventListener(){}},console};
vm.createContext(sandbox);
vm.runInContext(source.replace('  if(document.readyState','  globalThis.api={assessPrediction,makePrototypeGuard};\n  if(document.readyState'),sandbox);
const {assessPrediction,makePrototypeGuard}=sandbox.api;
const labels=['Other','Possum','Rat'];
const guard=labels.map((label,i)=>({label,prototype:labels.map((_,j)=>i===j?1:0),minimumSimilarity:0.8}));
assert.match(assessPrediction([.01,.95,.04],[0,0,1],labels,guard).decision,/Uncertain/,'A 95% Possum score must be rejected when nearest prototype is Rat');
assert.match(assessPrediction([.01,.95,.04],[1,1,1],labels,guard).decision,/Uncertain/,'A high score must not bypass a failed similarity bound');
assert.equal(assessPrediction([.01,.95,.04],[0,1,0],labels,guard).decision,'Possum');
assert.match(assessPrediction([.01,.95,.04],[0,1,0],labels,[]).decision,/Uncertain/,'Missing guard must fail closed');
assert.throws(()=>assessPrediction([NaN,.95,.04],[0,1,0],labels,guard));
const x=new Float32Array([1,0,0,0,1,0,0,0,1]),y=new Int32Array([0,1,2]);
const trained=makePrototypeGuard(x,y,x,y,3,labels);
assert.equal(trained.length,3);
assert.equal(trained[2].label,'Rat');
assert.equal(trained[2].minimumSimilarity,1);
assert.throws(()=>makePrototypeGuard(x,y,new Float32Array([1,0,0]),new Int32Array([0]),3,labels),'Every class needs validation data');
console.log('PASS: safety decisions, 95% disagreement, out-of-domain rejection, invalid output, class guard construction');
